// EPOS ARMv7 PMU Events Declaration

#include <architecture/pmu.h>

#ifdef __riscv__

__BEGIN_SYS

RV32_PMU::Event RV32_PMU::_monitored_events[RV32_PMU::CHANNELS] = {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
};

const RV32_PMU::Event RV32_PMU::_events[RV32_PMU::EVENTS] = {

    RV32_PMU::EXCEPTION_TAKEN                                 ,
    RV32_PMU::INTEGER_LOAD_INSTRUCTION_RETIRED                ,
    RV32_PMU::INTEGER_STORE_INSTRUCTION_RETIRED               ,
    RV32_PMU::ATOMIC_MEMORY_OPERATION_RETIRED                 ,
    RV32_PMU::SYSTEM_INSTRUCTION_RETIRED                      ,
    RV32_PMU::INTEGER_ARITHMETIC_INSTRUCTION_RETIRED          ,
    RV32_PMU::CONDITIONAL_BRANCH_RETIRED                      ,
    RV32_PMU::JAL_INSTRUCTION_RETIRED                         ,
    RV32_PMU::JALR_INSTRUCTION_RETIRED                        ,
    RV32_PMU::INTEGER_MULTIPLICATION_INSTRUCTION_RETIRED      ,
    RV32_PMU::INTEGER_DIVISION_INSTRUCTION_RETIRED            ,
    RV32_PMU::FLOATING_POINT_LOAD_INSTRUCTION_RETIRED         ,
    RV32_PMU::FLOATING_POINT_STORE_INSTRUCTION_RETIRED        ,
    RV32_PMU::FLOATING_POINT_ADDITION_RETIRED                 ,
    RV32_PMU::FLOATING_POINT_MULTIPLICATION_RETIRED           ,
    RV32_PMU::FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED       ,
    RV32_PMU::FLOATING_POINT_DIVISION_OR_SQUARE_ROOT_RETIRED  ,
    RV32_PMU::OTHER_FLOATING_POINT_INSTRUCTION_RETIRED        ,

    RV32_PMU::LOAD_USE_INTERLOCK                  ,
    RV32_PMU::LONG_LATENCY_INTERLOCK              ,
    RV32_PMU::CSR_READ_INTERLOCK                  ,
    RV32_PMU::INSTRUCTION_CACHE_ITIM_BUSY         ,
    RV32_PMU::DATA_CACHE_DTIM_BUSY                ,
    RV32_PMU::BRANCH_DIRECTION_MISPREDICTION      ,
    RV32_PMU::BRANCH_JUMP_TARGET_MISPREDICTION    ,
    RV32_PMU::PIPELINE_FLUSH_FROM_CSR_WRITE       ,
    RV32_PMU::PIPELINE_FLUSH_FROM_OTHER_EVENT     ,
    RV32_PMU::INTEGER_MULTIPLICATION_INTERLOCK    ,
    RV32_PMU::FLOATING_POINT_INTERLOCK            ,

    RV32_PMU::INSTRUCTION_CACHE_MISS                      ,
    RV32_PMU::DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS  ,
    RV32_PMU::DATA_CACHE_WRITEBACK                        ,
    RV32_PMU::INSTRUCTION_TLB_MISS                        ,
    RV32_PMU::DATA_TLB_MISS
};




__END_SYS

#endif
